### ISSUE TITLE
Some Questions About Dataset Results

### ISSUE THREAD

**Issue by muzi-Lu** [sijieaaa/RobustLoc#4]
Hello, Thank you for your open source code contribution.

There are the following questions:
1. Coordinet is not open source and does not have data for testing models in 4Seasons, so how did you test Coordinet in 4Seasons?
2.Perturbed RobotCar can be considered as another scenario of RobotCar, on Perturbed RobotCar, all models have Mean and Median data results, but on RobotCar, The data of the model is a lot of incomplete (such as Loop (within-day)), and it has been tested in Perturbed Robotcar, can't it be tested again on Robotcar?

Hope to get your reply.

**Comment by sijieaaa** [comment]
Hi,

1. We reimplement Coodinet by ourselves, and we test it in 4Seasons and Perturbed RobotCar.
2. The results in RobotCar are all from the respective papers. Since some papers do not provide the complete results, we leave them blank. Subsequently, we reimplement some models and test them in 4Seasons and Perturbed RobotCar. Thus the results in these two datasets are complete.
 
Thanks.

**Comment by muzi-Lu** [comment]
Thank you for your immediate reply.That helps me a lot!!!
close the issue
